CATEGORY_GENERAL = "general"
CATEGORY_REALTIME = "realtime"
CATEGORY_CAMERA = "camera"
CATEGORY_TASK = "task"
CATEGORY_MIXED = "mixed"
INTENT_OPEN = "open"
INTENT_PLAY = "play"
INTENT_CAMERA = "camera"
INTENT_OPEN_WEBCAM = "open webcam"
INTENT_CLOSE_WEBCAM = "close webcam"
INTENT_GENERATE_IMAGE = "generate image"
INTENT_CONTENT = "content"
INTENT_GOOGLE_SEARCH = "google search"
INTENT_YOUTUBE_SEARCH = "youtube search"
INTENT_CHAT = "chat"
INTENT_CALCULATE = "calculate"
INTENT_SITE_SEARCH = "site search"
INTENT_REMINDER = "reminder"
INTENT_UNKNOWN = "unknown"

HEAVY_INTENTS = {INTENT_GENERATE_IMAGE, INTENT_CONTENT}

INSTANT_INTENTS = {
    INTENT_OPEN, INTENT_PLAY, INTENT_CAMERA,
    INTENT_OPEN_WEBCAM, INTENT_CLOSE_WEBCAM,
    INTENT_GOOGLE_SEARCH, INTENT_YOUTUBE_SEARCH,
    INTENT_CALCULATE, INTENT_SITE_SEARCH, INTENT_REMINDER,
}

ROUTE_TO_INTENT = {
    "open": INTENT_OPEN,
    "play": INTENT_PLAY,
    "camera": INTENT_CAMERA,
    "open_webcam": INTENT_OPEN_WEBCAM,
    "close_webcam": INTENT_CLOSE_WEBCAM,
    "generate_image": INTENT_GENERATE_IMAGE,
    "content": INTENT_CONTENT,
    "google_search": INTENT_GOOGLE_SEARCH,
    "youtube_search": INTENT_YOUTUBE_SEARCH,
    "calculate": INTENT_CALCULATE,
    "site_search": INTENT_SITE_SEARCH,
    "reminder": INTENT_REMINDER,
    "general": INTENT_CHAT,
    "realtime": INTENT_CHAT,
}